/*
 * main.c
 *
 *  Created on: 18 mar 2022
 *      Author: asier
 */

#include <stdio.h>
#include "sqlite3.h"
#include <string.h>
#include <stdlib.h>
#include <stdbool.h>

void initBD(){
	sqlite3 *db;
	sqlite3_stmt *stmt;
	int result;

	sqlite3_open("supermercadoDB.sqlite", &db);


	char *sql = "DROP TABLE IF EXISTS SUPERMERCADO;"
			"CREATE TABLE SUPERMERCADO (COD_S INT PRIMARY KEY NOT NULL,  NOM_S VARCHAR(100),  DIR_S VARCHAR(100),TLF_S INT ,  METROS_CUADRADOS_S DOUBLE, COD_CIU INT FOREIGN KEY REFERENCES CIUADAD(COD_CIU) );"
			"DROP TABLE IF EXISTS PROVINCIA;"
			"CREATE TABLE PROVINCIA ( COD_PROV INT PRIMARY KEY NOT NULL,  NOM_PROV VARCHAR(100));"
			"DROP TABLE IF EXISTS CIUDAD;"
			"CREATE TABLE CIUDAD (COD_CIU INT PRIMARY KEY NOT NULL,  NOM_CIU VARCHAR(100), COD_PROV INT FOREIGN KEY REFERENCES PROVINCIA(COD_PROV));"
			"DROP TABLE IF EXISTS EMPLEADO;"
			"CREATE TABLE EMPLEADO ( DNI_EMP VARCHAR(100) PRIMARY KEY NOT NULL,  NOM_EMP VARCHAR(100), SALARIO_EMP DOUBLE, FECHA_NCTO_EMP DATE, DIR_EMP VARCHAR(100), DNI_JEFE VARCHAR(100) FOREIGN KEY REFENRENCES EMPLEADO(DNI_EMP) ); "
			"DROP TABLE IF EXISTS PRODUCTO;"
			"CREATE TABLE PRODUCTO (ID_PROD INT PRIMARY KEY NOT NULL, NOM_PROD VARCHAR(100), PRECIO_PROD DOUBLE, DESC_PROD VARVHAR(100));"
			"DROP TABLE IF EXISTS VENDE;"
			"CREATE TABLE VENDE ();"
			"DROP TABLE IF EXISTS TRABAJA;"
			"CREATE TABLE TRABAJA();";
}



int main() {

	return 0;
}


